### PR TITLE
Add docstrings, convenience version of `set_coords`

### LINKED ISSUE #180: Add docstrings
Under @lobingera's excellent care, Cairo seems to making steady strides. Another big step forward would be to add docstrings, and possibly Documenter.jl documentation; I still find myself consulting the source pretty frequently.

If it's useful, anyone who wishes to help document Cairo is more than welcome to steal (and update) material from [this blogpost](http://julialang.org/blog/2013/05/graphical-user-interfaces-part2) (source is https://github.com/JuliaLang/julialang.github.com/blob/master/blog/_posts/2013-05-23-graphical-user-interfaces-part2.md) and/or the Gtk documentation.

### PR DESCRIPTION
**Pull request by timholy**
CC @lobingera (partially fixes https://github.com/JuliaGraphics/Cairo.jl/issues/180).

I added the first test of `set_coords`, but then I decided that I wasn't sure I wanted to make testing of this package dependent on Gtk. So I commented it out. Thoughts welcome.

### CODE REVIEW

**Comment by lobingera** [comment]
you had a comment about "need to look inside code for docu"; you should mention, that set_coords also does clipping in this case.

**Comment by timholy** [comment]
You're referring to the `clip` call? I hadn't noticed that.

Should we document it, or change it? `set_coords` to me does not seem like a very good name for a function that sets the clip region. I've always just assumed it only affects the transformation.

**Comment by lobingera** [comment]
For a bigger picture: translate/scale/set_coordinate and similar actually introduce the classical 2D-CTM (https://www.cairographics.org/manual/cairo-Transformations.html or https://www.w3.org/TR/SVG/coords.html), I have this in a module (see e.g. the beginning of https://gist.github.com/lobingera/2e7a9e4f8579b82d9fe5) in my own experiments on drawing/rendering and i was for some time looking at https://github.com/FugroRoames/CoordinateTransformations.jl to integrate or use. 

To your question above: yes, if Graphics.jl is a light wrapper of underlaying rendering libraries, clip should be excluded and set_coord should have a single job. The standards might provide a better name here. Actually you're setting a transformation.

**Comment by timholy** [comment]
Does this seem reasonable?

**Comment by lobingera** [comment]
Yes.

**Pull request merged**
